version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: banco_treino-app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    env_file:
      - .env

  db:
    image: mysql:8.0
    container_name: banco_treino-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}' 
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
